"""Prepare review batches for external validation of empirical scenarios.

Reads all scenario JSONs and their .meta.json sidecars, produces compact
human-readable text blocks grouped into batches of 5, ordered by provenance
(hand-crafted first, then LLM-generated by quality desc).

Usage:
    python -m calibration.empirical.prepare_review_batch
"""

import json
import sys
from pathlib import Path

SCENARIOS_DIR = Path(__file__).parent / "scenarios"
REVIEW_DIR = Path(__file__).parent / "review"

REVIEWER_INSTRUCTIONS = """ISTRUZIONI PER IL REVIEWER: per ogni scenario, verifica:
1. Ground truth outcome: il numero è corretto? La fonte esiste?
2. Polling trajectory: i trend sono coerenti con dati pubblici noti?
3. Events: le date sono corrette? Mancano eventi critici?
4. Agents: i key stakeholder sono quelli giusti? Posizioni iniziali plausibili?
5. Shock magnitudes: le scale sono ragionevoli?
Rispondi con: PASS / CORRECTIONS [dettaglio] / REJECT [motivo]
"""

BATCH_SIZE = 5


def load_scenarios() -> list[dict]:
    """Load all scenario + metadata pairs."""
    scenarios = []
    for p in sorted(SCENARIOS_DIR.glob("*.json")):
        if p.name.endswith(".meta.json") or p.name == "manifest.json":
            continue
        with open(p) as f:
            scenario = json.load(f)

        meta_path = p.with_suffix("").with_suffix(".meta.json")
        meta = None
        if meta_path.exists():
            with open(meta_path) as f:
                meta = json.load(f)

        scenarios.append({"scenario": scenario, "meta": meta, "path": p})
    return scenarios


def format_scenario(entry: dict) -> str:
    """Format a single scenario as compact review text."""
    s = entry["scenario"]
    meta = entry["meta"]
    lines = []

    # Header
    lines.append(f"SCENARIO: {s['id']}")
    lines.append(f"Domain: {s['domain']} | Country: {s['country']}")
    lines.append(f"Period: {s['date_start']} -> {s['date_end']} | Rounds: {s['n_rounds']}")
    lines.append("")

    # Outcome
    gt = s["ground_truth_outcome"]
    lines.append(f"OUTCOME: {gt['pro_pct']}% pro | Source: {gt['source']}")
    lines.append(f"  Type: {gt['type']}")
    lines.append("")

    # Polling provenance lookup
    poll_prov = []
    if meta:
        poll_prov = meta.get("field_provenance", {}).get("polling_trajectory", [])

    # Polling trajectory
    lines.append("POLLING TRAJECTORY:")
    for i, p in enumerate(s["polling_trajectory"]):
        pro = f"{p['pro_pct']}%" if p["pro_pct"] is not None else "null"
        against = f"{p.get('against_pct', '?')}%" if p.get("against_pct") is not None else "?"
        undec = f"{p.get('undecided_pct', '?')}%" if p.get("undecided_pct") is not None else "?"
        n = f"n={p['sample_size']}" if p.get("sample_size") else "n=?"
        prov = poll_prov[i].upper().replace("_", " ") if i < len(poll_prov) else "?"
        # Truncate source to keep compact
        src = (p.get("source") or "?")[:100]
        lines.append(f"  R{p['round']} [{p['date']}]: {pro} vs {against} undec {undec} ({n}) [{prov}]")
        lines.append(f"     src: {src}")
    lines.append("")

    # Events provenance lookup
    evt_prov = []
    if meta:
        evt_prov = meta.get("field_provenance", {}).get("events", [])

    # Events
    lines.append("KEY EVENTS:")
    for i, ev in enumerate(s.get("events", [])):
        prov = evt_prov[i].upper().replace("_", " ") if i < len(evt_prov) else "?"
        desc = ev["description"][:90]
        src = (ev.get("source") or "no source")[:80]
        lines.append(
            f"  R{ev['round']} [{ev.get('date', '?')}]: {desc}"
        )
        lines.append(
            f"     shock: {ev['shock_magnitude']:.1f} x {ev['shock_direction']:+.1f} | {src} [{prov}]"
        )
    lines.append("")

    # Agents (top 5 by influence)
    agents_sorted = sorted(s.get("agents", []), key=lambda a: a.get("influence", 0), reverse=True)
    lines.append(f"AGENTS (top 5 of {len(agents_sorted)} by influence):")
    for a in agents_sorted[:5]:
        lines.append(
            f"  {a['name']} ({a['type']}): pos={a['initial_position']:+.1f} inf={a['influence']:.2f}"
        )
    lines.append("")

    # Covariates
    c = s.get("covariates", {})
    lines.append("COVARIATES:")
    lines.append(
        f"  polarization={c.get('initial_polarization', '?')}, "
        f"event_vol={c.get('event_volatility', '?')}, "
        f"elite_conc={c.get('elite_concentration', '?')}, "
        f"trust={c.get('institutional_trust', '?')}, "
        f"undecided={c.get('undecided_share', '?')}"
    )
    lines.append("")

    # Metadata summary
    is_handcrafted = meta is None
    generator = "hand_crafted" if is_handcrafted else "llm_generated"

    lines.append("METADATA:")
    lines.append(f"  Generator: {generator}")

    if meta:
        fp = meta.get("field_provenance", {})
        verified_count = 0
        estimated_fields = []
        total_fields = 0

        # Count verified vs estimated
        for field, prov in fp.items():
            if isinstance(prov, list):
                for p in prov:
                    total_fields += 1
                    if "verified" in p:
                        verified_count += 1
                    else:
                        estimated_fields.append(field)
                        break  # count field once
            else:
                total_fields += 1
                if "verified" in prov:
                    verified_count += 1
                else:
                    estimated_fields.append(field)

        pct = round(100 * verified_count / total_fields, 0) if total_fields else 0
        lines.append(f"  Fields verified: {verified_count}/{total_fields} ({pct:.0f}%)")
        if estimated_fields:
            lines.append(f"  LLM-estimated: {', '.join(estimated_fields)}")

        vs = meta.get("verification_summary", {})
        lines.append(
            f"  Polling verified: {vs.get('polling_verified_pct', '?')}% | "
            f"Events verified: {vs.get('events_verified_pct', '?')}%"
        )
    else:
        lines.append("  All fields human-authored (no .meta.json)")

    # Notes (truncated)
    if s.get("notes"):
        lines.append(f"\nNOTES: {s['notes'][:200]}")

    return "\n".join(lines)


def quality_score_for(entry: dict) -> float:
    """Extract quality score from meta or default to 100 for hand-crafted."""
    if entry["meta"] is None:
        return 100.0
    vs = entry["meta"].get("verification_summary", {})
    # Use polling verified % as proxy for quality ordering
    return vs.get("polling_verified_pct", 50.0)


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        help="Only include scenarios listed in manifest.json (useful for batch2-only review)",
    )
    parser.add_argument(
        "--start-batch",
        type=int,
        default=1,
        help="Starting batch number (default: 1)",
    )
    args = parser.parse_args()

    scenarios = load_scenarios()
    if not scenarios:
        print(f"No scenarios found in {SCENARIOS_DIR}")
        sys.exit(1)

    # Filter to manifest-only if requested
    if args.manifest_only:
        manifest_path = SCENARIOS_DIR / "manifest.json"
        if manifest_path.exists():
            with open(manifest_path) as f:
                manifest = json.load(f)
            manifest_ids = {s["id"] for s in manifest.get("scenarios", [])}
            scenarios = [e for e in scenarios if e["scenario"]["id"] in manifest_ids]
            print(f"  Filtered to {len(scenarios)} scenarios from manifest")
        else:
            print("  WARNING: manifest.json not found, using all scenarios")

    # Split into hand-crafted (no meta) and LLM-generated
    handcrafted = [e for e in scenarios if e["meta"] is None]
    generated = [e for e in scenarios if e["meta"] is not None]

    # Sort generated by quality score desc
    generated.sort(key=quality_score_for, reverse=True)

    # Order: handcrafted first, then generated
    ordered = handcrafted + generated

    # Create batches
    batches = []
    for i in range(0, len(ordered), BATCH_SIZE):
        batches.append(ordered[i:i + BATCH_SIZE])

    # Write batches
    REVIEW_DIR.mkdir(parents=True, exist_ok=True)

    batch_offset = args.start_batch - 1

    for i, batch in enumerate(batches):
        batch_num = i + 1 + batch_offset
        if batch_num == 1 and all(e["meta"] is None for e in batch):
            filename = "review_batch_1_handcrafted.txt"
        else:
            filename = f"review_batch_{batch_num}.txt"

        parts = [REVIEWER_INSTRUCTIONS.strip(), ""]
        ids = [e["scenario"]["id"] for e in batch]
        parts.append(f"BATCH {batch_num} — {len(batch)} scenarios: {', '.join(ids)}")
        parts.append("=" * 70)
        parts.append("")

        for j, entry in enumerate(batch):
            parts.append("-" * 70)
            parts.append(format_scenario(entry))
            parts.append("")

        content = "\n".join(parts)

        out_path = REVIEW_DIR / filename
        with open(out_path, "w") as f:
            f.write(content)

        # Rough token estimate (1 token ~ 4 chars)
        est_tokens = len(content) // 4
        print(f"  {filename}: {len(batch)} scenarios, ~{est_tokens} tokens, {len(content)} chars")

    print(f"\n  Total: {len(ordered)} scenarios in {len(batches)} batches")
    print(f"  Output: {REVIEW_DIR}/")


if __name__ == "__main__":
    main()
