"use client";

import dynamic from "next/dynamic";
import SectionHeader from "@/components/ui/SectionHeader";
import ScrollReveal from "@/components/ui/ScrollReveal";

const ReactMarkdown = dynamic(() => import("react-markdown"), { ssr: false });
const remarkGfm = dynamic(() => import("remark-gfm").then((m) => m.default ?? m), {
  ssr: false,
}) as any;

interface Props {
  markdown: string;
}

export default function ReportSection({ markdown }: Props) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Simulation Report</title>
        <style>
          body {
            font-family: 'Georgia', serif;
            max-width: 700px;
            margin: 40px auto;
            padding: 0 20px;
            color: #1a1a1a;
            line-height: 1.7;
            font-size: 14px;
          }
          h1 { font-size: 24px; margin-top: 40px; }
          h2 { font-size: 20px; margin-top: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
          h3 { font-size: 16px; margin-top: 24px; }
          table { border-collapse: collapse; width: 100%; margin: 16px 0; }
          th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; font-size: 13px; }
          th { background: #f3f4f6; font-weight: 600; }
          blockquote { border-left: 3px solid #3b82f6; padding-left: 16px; color: #4b5563; margin: 16px 0; }
          code { background: #f3f4f6; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
          .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #3b82f6; }
          .header h1 { margin: 0; font-size: 28px; }
          .header p { color: #6b7280; margin-top: 8px; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 11px; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Simulation Report</h1>
          <p>DigitalTwinSim — AI-Powered Multi-Agent Simulation</p>
        </div>
        <div id="content"></div>
        <div class="footer">
          <p>Generated by DigitalTwinSim</p>
        </div>
      </body>
      </html>
    `);

    const html = markdown
      .replace(/^### (.*$)/gm, "<h3>$1</h3>")
      .replace(/^## (.*$)/gm, "<h2>$1</h2>")
      .replace(/^# (.*$)/gm, "<h1>$1</h1>")
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/^> (.*$)/gm, "<blockquote>$1</blockquote>")
      .replace(/^- (.*$)/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
      .replace(/\n\n/g, "</p><p>")
      .replace(/^(?!<[hublop])/gm, "<p>")
      .replace(/<p><\/p>/g, "");

    printWindow.document.getElementById("content")!.innerHTML = html;
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  if (!markdown || markdown.trim().length === 0) {
    return (
      <section id="report" className="bg-white py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <SectionHeader title="Report" subtitle="Detailed analysis generated by the simulation engine." />
          <div className="bg-white border border-gray-200 rounded-xl p-12 text-center">
            <p className="text-gray-400 font-body">Report not available.</p>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="report" className="bg-white py-20 px-4">
      <div className="max-w-4xl mx-auto">
        <SectionHeader
          title="Report"
          subtitle="Detailed analysis generated by the simulation engine."
        />

        <ScrollReveal>
          <div className="flex justify-end mb-6">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-sans font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-500 transition-colors shadow-sm"
            >
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
              </svg>
              Download / Print
            </button>
          </div>

          <article className="prose prose-lg max-w-none prose-headings:text-gray-900 prose-p:text-gray-700 prose-strong:text-gray-800 prose-blockquote:border-blue-500 prose-blockquote:text-gray-500 prose-code:text-cyan-600 prose-code:bg-gray-100 prose-a:text-cyan-600 prose-table:text-gray-700 prose-th:bg-gray-100 prose-th:text-gray-800 prose-td:border-gray-300 prose-th:border-gray-300">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
          </article>
        </ScrollReveal>
      </div>
    </section>
  );
}
